// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: fileDuplicateFinder.proto

package fileduppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DuplicateFinder_UploadFiles_FullMethodName = "/DuplicateFinder/UploadFiles"
)

// DuplicateFinderClient is the client API for DuplicateFinder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DuplicateFinderClient interface {
	UploadFiles(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileData, DuplicateResult], error)
}

type duplicateFinderClient struct {
	cc grpc.ClientConnInterface
}

func NewDuplicateFinderClient(cc grpc.ClientConnInterface) DuplicateFinderClient {
	return &duplicateFinderClient{cc}
}

func (c *duplicateFinderClient) UploadFiles(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileData, DuplicateResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DuplicateFinder_ServiceDesc.Streams[0], DuplicateFinder_UploadFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileData, DuplicateResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DuplicateFinder_UploadFilesClient = grpc.ClientStreamingClient[FileData, DuplicateResult]

// DuplicateFinderServer is the server API for DuplicateFinder service.
// All implementations must embed UnimplementedDuplicateFinderServer
// for forward compatibility.
type DuplicateFinderServer interface {
	UploadFiles(grpc.ClientStreamingServer[FileData, DuplicateResult]) error
	mustEmbedUnimplementedDuplicateFinderServer()
}

// UnimplementedDuplicateFinderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDuplicateFinderServer struct{}

func (UnimplementedDuplicateFinderServer) UploadFiles(grpc.ClientStreamingServer[FileData, DuplicateResult]) error {
	return status.Errorf(codes.Unimplemented, "method UploadFiles not implemented")
}
func (UnimplementedDuplicateFinderServer) mustEmbedUnimplementedDuplicateFinderServer() {}
func (UnimplementedDuplicateFinderServer) testEmbeddedByValue()                         {}

// UnsafeDuplicateFinderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DuplicateFinderServer will
// result in compilation errors.
type UnsafeDuplicateFinderServer interface {
	mustEmbedUnimplementedDuplicateFinderServer()
}

func RegisterDuplicateFinderServer(s grpc.ServiceRegistrar, srv DuplicateFinderServer) {
	// If the following call pancis, it indicates UnimplementedDuplicateFinderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DuplicateFinder_ServiceDesc, srv)
}

func _DuplicateFinder_UploadFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DuplicateFinderServer).UploadFiles(&grpc.GenericServerStream[FileData, DuplicateResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DuplicateFinder_UploadFilesServer = grpc.ClientStreamingServer[FileData, DuplicateResult]

// DuplicateFinder_ServiceDesc is the grpc.ServiceDesc for DuplicateFinder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DuplicateFinder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DuplicateFinder",
	HandlerType: (*DuplicateFinderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFiles",
			Handler:       _DuplicateFinder_UploadFiles_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "fileDuplicateFinder.proto",
}
